apiVersion: v1
kind: Template
labels:
  template: thoth-cleanup-cronjob-buildconfig
  thoth: 0.1.0
metadata:
  name: thoth-cleanup-cronjob-buildconfig
  annotations:
    description: This is Thoth CleanUp CronJob BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Thoth User API BuildConfig
    version: 0.1.0
    tags: poc,thoth,thoth-user-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is Thoth CleanUp CronJob BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: cleanup-cronjob
  spec:
    name: latest
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: thoth-core
    name: cleanup-cronjob
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "cleanup-cronjob:${IMAGE_STREAM_TAG}"
    runPolicy: Serial
    source:
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange

parameters:
- description: Git repository for Thoth's User API
  displayName: Thoth user-api git repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/cleanup-job'

- description: Git repository for Thoth's User API
  displayName: Thoth user-api git reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'
