apiVersion: v1
kind: Template
labels:
  template: cleanup-cronjob
  thoth: 0.1.0
metadata:
  name: cleanup-cronjob
  annotations:
    description: This is Thoth Core - Cleanup Job
    openshift.io/display-name: "Thoth: Cleanup Job"
    version: 0.1.0
    tags: poc,thoth,ai-stacks,graph
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Cleanup Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: cleanup
    labels:
      app: thoth-core
  spec:
    schedule: "@weekly"
    suspend: ${THOTH_SUSPEND_JOB}
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            serviceAccountName: analyzer
            containers:
            - image: cleanup-job
              name: cleanup
              env:
               - name: KUBERNETES_VERIFY_TLS
                 value: "0"
               - name: THOTH_MIDDLETIER_NAMESPACE
                 valueFrom:
                   configMapKeyRef:
                     key: middletier-namespace
                     name: thoth
               - name: THOTH_ANALYZER_CLEANUP_TIME
                 valueFrom:
                  configMapKeyRef:
                    key: analyzer-cleanup-time
                    name: thoth
               - name: KUBERNETES_API_URL
                 value: 'https://kubernetes.default.svc.cluster.local'
               - name: THOTH_LOG_CLEANUP_JOB
                 value: 'DEBUG'
               - name: RSYSLOG_HOST
                 valueFrom:
                  configMapKeyRef:
                    key: rsyslog-host
                    name: thoth
               - name: RSYSLOG_PORT
                 valueFrom:
                  configMapKeyRef:
                    key: rsyslog-port
                    name: thoth
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "250m"
            restartPolicy: OnFailure

parameters:
  - displayName: Suspend CronJob run
    description: Suspend CronJob run
    required: true
    name: THOTH_SUSPEND_JOB
    value: true

